# Site settings
brand: Fuzzy Bearings
title: Blog
subtitle: limited visibility and signficant course correction
subtitle: because visbility is limited and we could use signficant course correction
subtitle: software - because visbility is limited
description: > # this means to ignore newlines until "baseurl:"
  Blog | Fuzzy Bearings
baseurl: ""
url: "http://blog.fuzzybearings.com"
twitter_username: FuzzyBearings
github_username:  FuzzyBearings

markdown: kramdown
exclude: [go.sh]
